### ISSUE TITLE
Main page freezes after adding a new Tool

### ISSUE THREAD

**Issue by wmorian** [wmorian/ToolCat#3]
Steps to reproduce:

1. Load the page
2. click on "Add Tool" (opens modal)
3. Fill the form
4. Submit the tool (closes modal)
5. Main page freezes. 
    a. No element can be clicked. 
    b. Mouse-over shows no reaction.

@CorinLUSI can you confirm if it is the same for you?

**Comment by CorinLUSI** [comment]
it was missing the modal.close() function inside the submit tool function
